#!/bin/zsh
#
# ------------------------------------------------------
# 2023-10-17  (deprecated)
# USEAGE > tmux new-session -tX   which uses ~/.tmux.conf
# creates new session called "X"
# ------------------------------------------------------
#
#
#
# ------------------------------------------------------
#	THIS CODE for REFERENCE ONlY - do not use
# ------------------------------------------------------
#
# - changed status-style
#   PURPOSE:    Replaces ~/.tmux.conf with zsh script
#   NOTE:       Be sure no ~/.tmux.conf
#               Be sure no other sessions
#
#   TODO:   !so how does -A work?
#   2023-06-01
#   -   escape-time?
j
SESSION=jimSession

## experimental
set-option -sg escape-time 10

#   -d detach all other sessions
#   -A if $SESSION exits, attach to it
#   -s create $SESSIION othewise
tmux new-session -d -A -s $SESSION


#   tmux creates first window when session created; 
tmux rename-window -t $SESSION:0  ZERO
tmux new-window -t $SESSION:1 -n NVIM
tmux new-window -t $SESSION:2 -n TWO
tmux new-window -t $SESSION:3 -n THREE
tmux new-window -t $SESSION:4 -n FOUR
tmux new-window -t $SESSION:5 -n free

tmux select-window -t $SESSION:1


##  BIND-KEY
## USAGE:   hold control & shift key, tap left or right arrow
#   FAIL: (why?)
#
#   -n  normal, ie do not use prefix
# tmux bind-key -n C-S-Left previous-window
# tmux bind-key -n C-S-Right next-window

# Not sure
tmux bind-key r source-file ~/.tmux.conf \; display-message " Config reloaded.."

# Works
tmux bind-key -n C-Left previous-window 
tmux bind-key -n C-Right next-window

#
tmux -2 attach-session -t $SESSION 

#
# 	---------------------
#   set-option status-style 
# 	---------------------
# 	-a  adds
tmux set-option -g status-style fg=red  # on acer
tmux set-option -ga status-style bg=black # on acer
